@baseUrl=http://localhost:8000
@botToken={{$dotenv BOT_TOKEN}}

###
POST https://api.telegram.org/bot{{botToken}}/setWebhook HTTP/1.1
Content-Type: application/json

{
    "url": "{{$dotenv WEBHOOK_URL}}",
    "secret_token": "{{$dotenv BOT_WEBHOOK_TOKEN}}",
    "allowed_updates": [
      "message"
    ]
}

###
GET https://api.telegram.org/bot{{botToken}}/getWebhookInfo HTTP/1.1

###
POST {{baseUrl}}/bot/ HTTP/1.1
Content-Type: application/json

{
    
}