# Generated by Django 5.2 on 2026-02-28 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0004_alter_planttype_planting_period_and_more"),
        ("diary", "0002_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SeedStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество семян"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="seed_stocks",
                        to="catalogs.planttype",
                        verbose_name="Тип",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seed_stocks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "variety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="seed_stocks",
                        to="catalogs.plantvariety",
                        verbose_name="Сорт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запас семян",
                "verbose_name_plural": "Запасы семян",
                "ordering": ("type__name", "variety__name"),
                "unique_together": {("user", "type", "variety")},
            },
        ),
    ]
