# Generated by Django 5.1.6 on 2025-02-21 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlantType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ИД"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Код")),
                ("name", models.CharField(max_length=128, verbose_name="Наименование")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "duration_days",
                    models.IntegerField(verbose_name="Срок созревания (дн.)"),
                ),
            ],
            options={
                "verbose_name": "Тип",
                "verbose_name_plural": "Типы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlantOperation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ИД"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("watering", "Полив"),
                            ("fertilizing", "Подкормка"),
                            ("hardening", "Закаливание"),
                            ("hilling", "Окучивание"),
                        ],
                        max_length=32,
                        verbose_name="Операция",
                    ),
                ),
                (
                    "since_step",
                    models.CharField(
                        choices=[
                            ("10-seed_preparation", "Подготовка семян"),
                            ("20-sowing", "Посев"),
                            ("30-sprouting", "Всходы"),
                            ("40-transplanting", "Пересадка"),
                            ("50-planting_preparation", "Подготовка к высадке"),
                            ("60-planting", "Высадка"),
                            ("65-blooming", "Цветение"),
                            ("70-pinching_out", "Пасынкование"),
                            ("80-tie_up", "Подвязка"),
                            ("90-harvesting", "Сбор урожая"),
                        ],
                        max_length=32,
                        verbose_name="С этапа",
                    ),
                ),
                (
                    "until_step",
                    models.CharField(
                        choices=[
                            ("10-seed_preparation", "Подготовка семян"),
                            ("20-sowing", "Посев"),
                            ("30-sprouting", "Всходы"),
                            ("40-transplanting", "Пересадка"),
                            ("50-planting_preparation", "Подготовка к высадке"),
                            ("60-planting", "Высадка"),
                            ("65-blooming", "Цветение"),
                            ("70-pinching_out", "Пасынкование"),
                            ("80-tie_up", "Подвязка"),
                            ("90-harvesting", "Сбор урожая"),
                        ],
                        max_length=32,
                        verbose_name="По этап",
                    ),
                ),
                (
                    "delay_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ожидание (дн.)"
                    ),
                ),
                (
                    "interval_days",
                    models.IntegerField(verbose_name="Периодичность (дн.)"),
                ),
                (
                    "duration_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Продолжительность (дн.)"
                    ),
                ),
                (
                    "plant_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="operations",
                        to="catalogs.planttype",
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Операция",
                "verbose_name_plural": "Операции",
            },
        ),
        migrations.CreateModel(
            name="PlantStep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ИД"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("10-seed_preparation", "Подготовка семян"),
                            ("20-sowing", "Посев"),
                            ("30-sprouting", "Всходы"),
                            ("40-transplanting", "Пересадка"),
                            ("50-planting_preparation", "Подготовка к высадке"),
                            ("60-planting", "Высадка"),
                            ("65-blooming", "Цветение"),
                            ("70-pinching_out", "Пасынкование"),
                            ("80-tie_up", "Подвязка"),
                            ("90-harvesting", "Сбор урожая"),
                        ],
                        max_length=32,
                        verbose_name="Этап",
                    ),
                ),
                (
                    "plant_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="catalogs.planttype",
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Этап выращивания",
                "verbose_name_plural": "Этапы выращивания",
                "ordering": ["plant_type", "step"],
                "unique_together": {("plant_type", "step")},
            },
        ),
        migrations.CreateModel(
            name="PlantVariety",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ИД"
                    ),
                ),
                ("slug", models.SlugField(verbose_name="Код")),
                ("name", models.CharField(max_length=128, verbose_name="Наименование")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "duration_days",
                    models.IntegerField(verbose_name="Срок созревания (дн.)"),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="varieties",
                        to="catalogs.planttype",
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сорт",
                "verbose_name_plural": "Сорта",
                "ordering": ["name"],
                "unique_together": {("type", "slug")},
            },
        ),
    ]
