# Generated by Django 5.1.6 on 2025-02-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantoperation",
            name="operation",
            field=models.CharField(
                choices=[
                    ("watering", "💦 Полив"),
                    ("fertilizing", "🧪 Подкормка"),
                    ("hardening", "❄️ Закаливание"),
                    ("hilling", "🪨 Окучивание"),
                ],
                max_length=32,
                verbose_name="Операция",
            ),
        ),
        migrations.AlterField(
            model_name="plantoperation",
            name="since_step",
            field=models.CharField(
                choices=[
                    ("10-seed_preparation", "🌱🛠️ Подготовка семян"),
                    ("20-sowing", "🌱👐 Посев"),
                    ("30-sprouting", "🌱🌞 Всходы"),
                    ("40-transplanting", "🪴🚜 Пересадка"),
                    ("50-planting_preparation", "🌿🛠️ Подготовка к высадке"),
                    ("60-planting", "🌱🏞️ Высадка"),
                    ("65-blooming", "🌸🌼 Цветение"),
                    ("70-pinching_out", "✂️🌿 Пасынкование"),
                    ("80-tie_up", "🌿🪢 Подвязка"),
                    ("90-harvesting", "🧺🍅 Сбор урожая"),
                ],
                max_length=32,
                verbose_name="С этапа",
            ),
        ),
        migrations.AlterField(
            model_name="plantoperation",
            name="until_step",
            field=models.CharField(
                choices=[
                    ("10-seed_preparation", "🌱🛠️ Подготовка семян"),
                    ("20-sowing", "🌱👐 Посев"),
                    ("30-sprouting", "🌱🌞 Всходы"),
                    ("40-transplanting", "🪴🚜 Пересадка"),
                    ("50-planting_preparation", "🌿🛠️ Подготовка к высадке"),
                    ("60-planting", "🌱🏞️ Высадка"),
                    ("65-blooming", "🌸🌼 Цветение"),
                    ("70-pinching_out", "✂️🌿 Пасынкование"),
                    ("80-tie_up", "🌿🪢 Подвязка"),
                    ("90-harvesting", "🧺🍅 Сбор урожая"),
                ],
                max_length=32,
                verbose_name="По этап",
            ),
        ),
        migrations.AlterField(
            model_name="plantstep",
            name="step",
            field=models.CharField(
                choices=[
                    ("10-seed_preparation", "🌱🛠️ Подготовка семян"),
                    ("20-sowing", "🌱👐 Посев"),
                    ("30-sprouting", "🌱🌞 Всходы"),
                    ("40-transplanting", "🪴🚜 Пересадка"),
                    ("50-planting_preparation", "🌿🛠️ Подготовка к высадке"),
                    ("60-planting", "🌱🏞️ Высадка"),
                    ("65-blooming", "🌸🌼 Цветение"),
                    ("70-pinching_out", "✂️🌿 Пасынкование"),
                    ("80-tie_up", "🌿🪢 Подвязка"),
                    ("90-harvesting", "🧺🍅 Сбор урожая"),
                ],
                max_length=32,
                verbose_name="Этап",
            ),
        ),
    ]
