# Generated by Django 5.1.7 on 2025-05-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0002_alter_plantoperation_operation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planttype",
            name="planting_period",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Период высадки"
            ),
        ),
        migrations.AddField(
            model_name="plantvariety",
            name="planting_period",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Период высадки"
            ),
        ),
    ]
