# Generated by Django 5.2 on 2025-05-04 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0003_planttype_planting_period_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planttype",
            name="planting_period",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Неверный формат периода высадки. Используйте формат 'DD.MM-DD.MM', где MM - месяц в римской записи (I-XII).",
                        regex="^(0[1-9]|[12][0-9]|3[01])\\.(I|II|III|IV|V|VI|VII|VIII|IX|X|XI|XII)-(0[1-9]|[12][0-9]|3[01])\\.(I|II|III|IV|V|VI|VII|VIII|IX|X|XI|XII)$",
                    )
                ],
                verbose_name="Период высадки",
            ),
        ),
        migrations.AlterField(
            model_name="plantvariety",
            name="planting_period",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Неверный формат периода высадки. Используйте формат 'DD.MM-DD.MM', где MM - месяц в римской записи (I-XII).",
                        regex="^(0[1-9]|[12][0-9]|3[01])\\.(I|II|III|IV|V|VI|VII|VIII|IX|X|XI|XII)-(0[1-9]|[12][0-9]|3[01])\\.(I|II|III|IV|V|VI|VII|VIII|IX|X|XI|XII)$",
                    )
                ],
                verbose_name="Период высадки",
            ),
        ),
    ]
