# Generated by Django 5.1.7 on 2026-03-03 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0004_alter_planttype_planting_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planttype",
            name="sowing_period",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Неверный формат периода посадки. Используйте формат 'DD.MM-DD.MM', где MM - месяц в римской записи (I-XII).",
                        regex="^(0[1-9]|[12][0-9]|3[01])\\.(I|II|III|IV|V|VI|VII|VIII|IX|X|XI|XII)-(0[1-9]|[12][0-9]|3[01])\\.(I|II|III|IV|V|VI|VII|VIII|IX|X|XI|XII)$",
                    )
                ],
                verbose_name="Период посадки",
            ),
        ),
        migrations.AddField(
            model_name="plantvariety",
            name="sowing_period",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Неверный формат периода посадки. Используйте формат 'DD.MM-DD.MM', где MM - месяц в римской записи (I-XII).",
                        regex="^(0[1-9]|[12][0-9]|3[01])\\.(I|II|III|IV|V|VI|VII|VIII|IX|X|XI|XII)-(0[1-9]|[12][0-9]|3[01])\\.(I|II|III|IV|V|VI|VII|VIII|IX|X|XI|XII)$",
                    )
                ],
                verbose_name="Период посадки",
            ),
        ),
    ]
